# Generated by Django 5.1.4 on 2025-11-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPestetica', '0001_initial'),
    ]

    operations = [
    ]
