# Generated by Django 5.1.4 on 2025-11-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPestetica', '0002_auto_20251111_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='hora_abertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='loja',
            name='hora_fechamento',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPestetica.loja')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('loja', 'dia_semana')},
            },
        ),
    ]
