# Generated by Django 5.1.4 on 2025-11-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPestetica', '0004_alter_horariofuncionamento_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='ERPestetica.loja')),
                ('servicos', models.ManyToManyField(related_name='profissionais', to='ERPestetica.servico')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='ERPestetica.profissional'),
        ),
    ]
