# Generated by Django 5.1.4 on 2025-11-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPestetica', '0005_profissional_agendamento_profissional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
    ]
