# Generated by Django 5.1.4 on 2025-11-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('queixa', models.TextField()),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
