# Generated by Django 5.1.4 on 2025-11-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='assinatura',
            new_name='assinatura_paciente',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='queixa',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alcool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alcool_frequencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alergias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alergias_quais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='assinatura_responsavel',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='condicoes_saude',
            field=models.TextField(blank=True, help_text='Lista como: Hipertensão; Diabetes; Doença Cardiovascular...'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='data_assinatura_paciente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='data_assinatura_responsavel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='data_ultimo_exame',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='drogas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='drogas_quais_frequencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='expectativas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='fez_tratamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='fumante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='fumo_quantidade_tempo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hospitalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hospitalizado_detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='medicamentos_detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='motivo_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='origem_encaminhamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='profissao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='responsavel_rg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='suplementos_quais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tempo_problema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_local',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_medico_qual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_medicamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_suplementos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
