# Generated by Django 5.2.7 on 2025-11-02 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRotina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('leitura', models.BooleanField(default=False)),
                ('arte_marcial', models.BooleanField(default=False)),
                ('limpar_casa', models.BooleanField(default=False)),
                ('musculacao', models.BooleanField(default=False)),
                ('tomar_agua', models.BooleanField(default=False)),
                ('alimentacao_saudavel', models.BooleanField(default=False)),
                ('pontos', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
