# Generated by Django 5.2.7 on 2025-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRotina', '0002_rotina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='badge',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='badge',
            name='requisito_pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='requisito_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='ultimo_checkin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
