# Generated by Django 5.2.7 on 2025-11-02 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRotina', '0003_delete_task_badge_descricao_badge_requisito_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='data_hora',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='pontos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
