# Generated by Django 5.2.7 on 2025-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRotina', '0004_rotina_enviado_alter_rotina_data_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotina',
            name='tomar_agua',
        ),
        migrations.AddField(
            model_name='rotina',
            name='copos_agua',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
