# Generated by Django 5.2.7 on 2025-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRotina', '0005_remove_rotina_tomar_agua_rotina_copos_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
