# Generated by Django 5.1.4 on 2025-02-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_contrato', models.DateField()),
                ('tipo', models.CharField(choices=[('freelancer', 'Freelancer'), ('fixo', 'Fixo (Contrato)')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('Fornecedor', 'Fornecedor'), ('colaborador', 'Colaborador'), ('cliente', 'Cliente'), ('prospeccao', 'Prospeccao')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('infraestrutura', 'Infraestrutura'), ('desenvolvimento', 'Desenvolvimento'), ('automacao', 'Automação'), ('suporte', 'Suporte'), ('consultoria', 'Consultoria')], default='hora', max_length=50)),
                ('modelo_cobranca', models.CharField(choices=[('hora', 'Hora'), ('projeto_fechado', 'Projeto Fechado'), ('mensalidade', 'Mensalidade'), ('retainer', 'Retainer')], max_length=50)),
                ('requisitos', models.CharField(blank=True, choices=[('acesso_a_conta', 'Acesso a Conta'), ('acesso_remoto', 'Acesso Remoto'), ('documentacao_rede', 'Documentação da Rede'), ('acesso_servidor', 'Acesso ao Servidor'), ('infraestrutura_basica', 'Infraestrutura Básica'), ('equipamento_rede', 'Equipamento de Rede')], max_length=100, null=True)),
                ('ferramentas', models.CharField(blank=True, choices=[('AnyDesk', 'AnyDesk'), ('pendrive', 'PenDrive'), ('powerapps', 'PowerApps'), ('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('pfsense', 'Pfsense'), ('mikrotik', 'Mikrotik'), ('power_apps', 'Power Apps'), ('github', 'GitHub'), ('azure', 'Azure'), ('aws', 'AWS'), ('docker', 'Docker'), ('sql_server', 'SQL Server')], max_length=100, null=True)),
                ('tempo_medio_execucao', models.CharField(choices=[('30_minutos', '30 minutos'), ('1_hora', '1 hora'), ('3_horas', '3 horas'), ('6_horas', '6 horas'), ('12_horas', '12 horas'), ('1_dia_util', '1 dia útil'), ('3_dias_uteis', '3 dias úteis'), ('5_dias_uteis', '5 dias úteis'), ('1_semana', '1 semana'), ('2_semanas', '2 semanas'), ('1_mes', '1 mês')], max_length=50)),
                ('nivel_complexidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('sob_demanda', 'Sob Demanda'), ('em_manutencao', 'Em Manutenção')], max_length=50)),
                ('documentacao', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
    ]
