# Generated by Django 5.1.4 on 2025-02-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppHome.contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('Parceria', 'Parceria'), ('Fornecedor', 'Fornecedor'), ('colaborador', 'Colaborador'), ('cliente', 'Cliente'), ('prospeccao', 'Prospeccao')], max_length=20),
        ),
    ]
