# Generated by Django 5.1.4 on 2025-02-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0002_remove_cliente_telefone_cliente_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('chamado', 'Chamado'), ('projeto', 'Projeto')], default='chamado', max_length=50)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('feito', 'Feito'), ('cancelado', 'Cancelado')], default='pendente', max_length=50)),
            ],
        ),
    ]
