# Generated by Django 5.1.4 on 2025-02-24 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0003_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppHome.cliente'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppHome.servico'),
        ),
    ]
