# Generated by Django 5.1.4 on 2025-02-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0004_demanda_cliente_demanda_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='cliente',
            new_name='solicitante',
        ),
    ]
