# Generated by Django 5.1.4 on 2025-02-25 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0008_alter_demanda_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_resolvidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
