# Generated by Django 5.1.4 on 2025-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0009_demanda_executor_alter_demanda_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
