# Generated by Django 5.1.4 on 2025-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0011_telegramlog_cliente_usuarios_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='escopo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='orcamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='prazos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsaveis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='riscos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
