# Generated by Django 5.2.7 on 2025-11-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0012_demanda_escopo_demanda_justificativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('leitura', models.BooleanField(default=False, verbose_name='Leitura (3 páginas)')),
                ('arte_marcial', models.BooleanField(default=False, verbose_name='Arte Marcial')),
                ('limpar_casa', models.BooleanField(default=False, verbose_name='Limpar Casa')),
                ('musculacao', models.BooleanField(default=False, verbose_name='Musculação')),
                ('tomar_agua', models.BooleanField(default=False, verbose_name='Tomar Água Correto')),
                ('alimentacao_saudavel', models.BooleanField(default=False, verbose_name='Alimentação Saudável')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
