# Generated by Django 5.2.7 on 2025-11-02 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0013_rotina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='alimentacao_saudavel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='arte_marcial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='leitura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='limpar_casa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='musculacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='tomar_agua',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🏆', max_length=10)),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
