# Generated by Django 5.2.7 on 2025-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0014_alter_rotina_alimentacao_saudavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='data_conquista',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='badge',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='badge',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pontos', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='AppHome.badge')),
            ],
        ),
    ]
