# Generated by Django 5.2.7 on 2025-11-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0015_remove_badge_data_conquista_remove_badge_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='rotina',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Rotina',
        ),
    ]
